### ISSUE TITLE
Can't replicate results disclosed on 'Classifying Norm Conflicts using Learned Semantic Representations'

### ISSUE THREAD

**Issue by semaraugusto** [mir-pucrs/norm-conflict-classification#1]
I've downloaded CoreNLP, FastText, the wiki_unigrams and was able to succesfully run the code provided on codes/svm.

I had to add some lines to the configuration file, with the SVM_C and BEST_SCORE parameters, but, after doing that, the svm_conflicts.py file got the metrics disclosed on the paper. 

However, the svm.py gets me this output:
```
2020-02-17 13:30:22,424 : INFO : - Accuracy: 0.521739
2020-02-17 13:30:22,425 : INFO : - Precision: 0.109091
2020-02-17 13:30:22,425 : INFO : - Recall: 0.200000
2020-02-17 13:30:22,425 : INFO : - F-score: 0.141176
```
Which is pretty far from the results provided. 

I'm running the code using the following command

```
python2 svm.py ../../data/10-fold.json ../../norm-conflict-classification-dataset/dataset/conflicts.csv ../../norm-conflict-classification/norm-conflict-classification-dataset/dataset/non_conflicts.csv -o ouptut.csv
```
Where conflicts.csv and non_conflicts.csv are the csv's provided here https://github.com/mir-pucrs/norm-conflict-classification-dataset

Embeddings where generated using the script provided on the scripts folder on this repository using the following command:

```
python2 create_embeddings.py ~/Projetos/norm-conflict-classification/norm-conflict-classification-dataset/dataset/non_conflicts.csv
```

Is there any documentation on how to replicate the results for the TypeC+Non (E_{concat}) approach?

**Comment by meneguzzi** [comment]
João, can you double check library versions for this?
Also, since the benchmarks are probably still in the group server, can you see if the folds are the same, but more importantly (and the thing I reckon is the culprit), that the code to generate the embeddings is the same?

**Comment by JoaoPauloAires** [comment]
I'm going to check this issue today and return with a solution as soon as possible.

**Comment by semaraugusto** [comment]
Got it... The configuration file is missing some lines, one of them is the BINARY one.

That leads python to calculate the results using the weighted method on the precision_recall_fscore_support function and calculate the mean.

With the settings.conf file like this:
```
# Number of folds in cross-validation
K=10

# Mode of merging vectors
MODES=offset,concat,mean

# Default mode
MODE=concat
BINARY=True
SVM_C=1
BEST_SCORE=f-score
```

I get these results:
```
2020-03-05 09:46:38,901 : INFO : - Accuracy: 0.695652
2020-03-05 09:46:38,901 : INFO : - Precision: 0.722222
2020-03-05 09:46:38,901 : INFO : - Recall: 0.590909
2020-03-05 09:46:38,901 : INFO : - F-score: 0.650000
```
They are still different from the results disclosed on the paper,
```
Accuracy: 0.7
Precision: 0.71
Recall: 0.64
F1: 0.66
```
But at least the results are close now.

**Comment by meneguzzi** [comment]
Thanks Semar! @JoaoPauloAires can you check his pull request at some point?
